var Text = {
	success: 'Success', 
	relogin: 'Login required', 
	instance_id_invalidated: 'Instance ID Invalidated', 
	cannot_get_qrcode: 'Cannot get QR Code', 
	cannot_connect_to_whatsapp: 'Cannot connect to Whatsapp on your phone', 
	authentication_failed: 'Authentication failed', 
	cannot_pin_chat: 'Cannot pin chat', 
	limit_pin_chat: 'Whatsapp can only give you up to 3 extra pins', 
	cannot_unpin_chat: 'Cannot unpin chat', 
	cannot_delete_chat: 'Cannot delete chat', 
	cannot_delete_message: 'Cannot delete message', 
	cannot_get_file: 'Cannot get file. File has been removed from Whatsapp server', 
	cannot_clear_chat: 'Cannot clear messages on this chat', 
	cannot_get_chat: 'Cannot get chats. Please try again later', 
	cannot_get_contact: 'Cannot get contact. Please try again later', 
	cannot_get_contacts: 'Cannot get contacts. Please try again later', 
	cannot_get_messages: 'Cannot get messages. Please try again later', 
	send_file_error: 'Failed to send file', 
	cannot_get_participants: 'Cannot get list of participants. Please try again later',
	send_message_error: 'Failed to send the message',
	logout_failed: 'Logout failed',
	message_limit: 'You have exceeded the maximum number of messages you can send per day',
	subscription_expired: 'Your subscription has expired. Renew your subscription so as not to interrupt your plan',
	whatsapp_live: 'WHATSAPP SERVER IS LIVE NOW',
}

module.exports = Text; 